// Lab 09 Data Module
unitDatabase["unit9"] = {
    id: "unit9",
    title: "Lab 09: Corporate Accounts",
    subheading: "Companies Act 2013, Schedule III Financial Statements Layout, Share Capital Hierarchy, and AS 4 Revised Proposed Dividend Disclosures",
    bites: [
        { tag: "Concept 01", title: "Legal Nature of a Joint Stock Company", desc: "A company is an artificial juridical person incorporated under the Companies Act 2013 with a separate legal entity, perpetual succession, common seal, and limited liability.", rule: "Liability Rule: Shareholder liability is strictly limited to the unpaid face value of subscribed shares." },
        { tag: "Concept 02", title: "Section 129 True & Fair Presentation", desc: "Under Section 129(1), financial statements must give a true and fair view of corporate state of affairs, comply with Section 133 accounting standards, and follow Schedule III vertical formats.", rule: "Statutory Override: Insurance and banking enterprises are governed by their respective specific sector statutes and regulator forms." },
        { tag: "Concept 03", title: "Schedule III Balance Sheet Architecture", desc: "Schedule III mandates a vertical Balance Sheet layout structured into: I. Equity and Liabilities (Shareholders' Funds, Non-Current Liabilities, Current Liabilities); II. Assets (Non-Current Assets, Current Assets).", rule: "Comparative Rule: Financial statements must include comparative figures for the immediately preceding reporting period." },
        { tag: "Concept 04", title: "Share Capital Hierarchy Tiers", desc: "Share capital is categorized into: 1. Authorised Capital (nominal ceiling); 2. Issued Capital; 3. Subscribed Capital; 4. Called-up Capital; 5. Paid-up Capital (net of calls-in-arrears).", rule: "Equity vs. Preference: Preference shares carry preferential rights to fixed dividends and capital repayment upon winding up." },
        { tag: "Concept 05", title: "Proposed Dividend & Revised AS 4", desc: "Under revised AS 4 / Ind AS 10 and Schedule III, proposed dividend is NOT a liability on the balance sheet date. It is disclosed in Notes to Accounts until formally approved by shareholders at the AGM.", rule: "Payment Mandate: Once declared at the AGM, approved dividends must be disbursed within 30 days." },
        { tag: "Concept 06", title: "Section 134 Board's Report & Signatures", desc: "Financial statements must be approved by the Board and signed by the chairperson or two directors (including MD), CEO, CFO, and Company Secretary, accompanied by the mandatory Board's Report.", rule: "Governance Rule: The Board's Report must include the Directors' Responsibility Statement and CSR disclosures." }
    ],
    sandbox: {
        initialState: { cash: 530000, liabilities: 18352100, equity: 26904900, revenue: 45350000, expenses: 41043000, currentStage: 1, score: 0 },
        stages: [
            { stage: 1, scenario: "Apex Shield drafts its corporate Statement of Profit and Loss: Revenue from Operations ₹4,45,40,000, Other Income ₹8,10,000, and Total Expenses ₹4,10,43,000.", question: "Calculate Profit Before Tax (PBT) and Profit After Tax (PAT) assuming a 30% corporate income tax rate.", options: [{ id: "A", text: "PBT: ₹43,07,000 | Tax (30%): ₹12,92,100 | PAT: ₹30,14,900 (Transferred to Reserves & Surplus)", isCorrect: true, financialImpact: { revenue: 45350000, expenses: 41043000, liabilities: 1292100, equity: 3014900 }, feedback: "Correct. PBT = ₹4,53,50,000 - ₹4,10,43,000 = ₹43,07,000. Tax @ 30% = ₹12,92,100. PAT = ₹30,14,900." }, { id: "B", text: "PBT: ₹35,00,000 | Tax: ₹10,50,000 | PAT: ₹24,50,000", isCorrect: false, misc: "MIS_PBT_CALCULATION_ERROR", feedback: "Incorrect. Total revenue includes revenue from operations plus other investment income." }] },
            { stage: 2, scenario: "The Board of Directors proposes a 10% dividend (₹25,00,000) on paid-up share capital of ₹2,50,00,000 at year-end before the AGM.", question: "Under AS 4 (Revised) and Schedule III, how is this proposed dividend presented in financial statements?", options: [{ id: "A", text: "Disclose in 'Notes to Accounts' only; do NOT record as a Balance Sheet provision/liability until approved at AGM", isCorrect: true, financialImpact: {}, feedback: "Correct. Revised AS 4 states proposed dividend is not an accrued liability on balance sheet date." }, { id: "B", text: "Debit P&L Account directly and show as a Current Provision Liability", isCorrect: false, misc: "MIS_PROPOSED_DIVIDEND_PROVISION_ERROR", feedback: "Incorrect. Under revised AS 4, proposed dividend cannot be booked as a liability prior to AGM shareholder approval." }] },
            { stage: 3, scenario: "Apex Shield has issued 10% Debentures of ₹50,00,000. Interest paid during the year is ₹2,00,000.", question: "What is the year-end adjustment for debenture interest in the financial statements?", options: [{ id: "A", text: "Charge ₹5,00,000 full finance cost to P&L (₹2L paid + ₹3L Outstanding Liability in Schedule III)", isCorrect: true, financialImpact: { expenses: 300000, liabilities: 300000 }, feedback: "Correct. Full 10% on ₹50L is ₹5,00,000. Unpaid ₹3,00,000 is shown under Other Current Liabilities in Schedule III." }, { id: "B", text: "Charge only ₹2,00,000 cash paid to P&L and ignore unpaid debenture interest", isCorrect: false, misc: "MIS_ACCRUAL_FINANCE_COST_OMISSION", feedback: "Incorrect. Accrual accounting requires full contractual interest of ₹5,00,000 to be charged with ₹3L accrued." }] }
        ]
    },
    exam: [
        { id: "u9_q1", question: "1. At every Annual General Meeting (AGM) under Section 129(2), the Board of Directors shall lay before the meeting:", options: [{ id: "A", text: "The statutory audit tax returns only", isCorrect: false, misc: "MIS_TAX_RETURN_AGM" }, { id: "B", text: "Financial statements for the financial year", isCorrect: true }], explanation: "Section 129(2) mandates that the Board of Directors shall lay financial statements before the annual general meeting." }
    ]
};