// Lab 11 Data Module: Insurance Regulations & Schedule B
unitDatabase["unit11"] = {
    id: "unit11",
    title: "Lab 11: Insurance Accounting Regulations & Schedule B",
    subheading: "IRDAI (Preparation of Financial Statements and Auditor's Report of Insurance Companies) Regulations 2000 & 2002",
    bites: [
        { tag: "Concept 01", title: "Statutory Authority & Scope", desc: "Under Section 11(1) of Insurance Act 1938 and Section 26 of IRDA Act 1999, IRDAI framed regulations governing non-life financial statements.", rule: "Insurance accounting regulations override general Companies Act Schedule III presentation." },
        { tag: "Concept 02", title: "4 Primary Financial Statements", desc: "Non-life insurers prepare: 1. Form A-RA (Revenue Account); 2. Form A-PL (Profit & Loss Account); 3. Form A-BS (Balance Sheet); 4. Receipts & Payments Account (Direct Method Cash Flow).", rule: "Separate Revenue Accounts are mandatory for Fire, Marine, and Miscellaneous segments." },
        { tag: "Concept 03", title: "15 Statutory Financial Schedules", desc: "Schedules 1 to 4: Premium, Claims, Commission, Operating Expenses. Schedules 5 to 7: Capital, Reserves, Borrowings. Schedules 8 to 15: Investments, Loans, Fixed Assets, Cash, Advances, Liabilities, Provisions.", rule: "Comparative figures for the immediately preceding financial year are mandatory." },
        { tag: "Concept 04", title: "5 Core IRDAI Accounting Principles", desc: "Part I of Schedule B defines 5 core principles: 1. Premium recognition over risk period; 2. Premium Deficiency Reserve (PDR); 3. Acquisition costs expensed as incurred; 4. Claims Incurred provisioning (inc. IBNR); 5. Segment Reporting.", rule: "Acquisition costs cannot be deferred or capitalized." },
        { tag: "Concept 05", title: "Statutory Auditor's Report Mandates", desc: "Auditors must certify true and fair view, compliance with IRDAI regulations, verification of investments, and proper valuation of assets.", rule: "Auditor must expressly confirm adherence to regulatory investment ceilings." },
        { tag: "Concept 06", title: "Management Report Disclosures", desc: "Annual reports must include a Management Report confirming registration validity, statutory payments, solvency margin adequacy, and risk management implementation.", rule: "Signed by Directors, CEO/Principal Officer, and Company Secretary." }
    ],
    sandbox: {
        initialState: { cash: 15000000, liabilities: 5000000, equity: 10000000, revenue: 0, expenses: 0, currentStage: 1, score: 0 },
        stages: [
            { stage: 1, scenario: "Apex Shield writes ₹80,00,000 Net Written Premium in Health. At year-end, expected future claims and servicing costs on active policies are estimated at ₹48,00,000, while the standard 50% URR reserve is ₹40,00,000.", question: "Under Part I Schedule B of IRDAI Regulations, what accounting provision is mandatory for the ₹8,00,000 deficit?", options: [{ id: "A", text: "Create an immediate Premium Deficiency Reserve (PDR) of ₹8,00,000 in Revenue Account and Balance Sheet", isCorrect: true, financialImpact: { expenses: 800000, liabilities: 800000 }, feedback: "Correct. Principle 2 mandates creating PDR whenever expected claims and expenses exceed unexpired risk reserves." }, { id: "B", text: "Defer the deficit to next year since actual claims have not yet been filed", isCorrect: false, misc: "MIS_PDR_DEFERRAL_VIOLATION", feedback: "Incorrect. Under IRDAI principles, PDR must be recognized as an expense and liability in the current period." }] },
            { stage: 2, scenario: "Apex Shield incurs ₹12,00,000 in agency acquisition commissions for commercial fire policies starting in the next financial quarter.", question: "How should acquisition costs be accounted for under IRDAI Accounting Principle 3?", options: [{ id: "A", text: "Expense 100% (₹12,00,000) in the accounting period in which they are incurred (Schedule 3)", isCorrect: true, financialImpact: { expenses: 1200000, cash: -1200000 }, feedback: "Correct. IRDAI Principle 3 mandates expensing acquisition costs in the period incurred without deferral." }, { id: "B", text: "Capitalize as Deferred Acquisition Cost (DAC) and amortize over 3 years", isCorrect: false, misc: "MIS_DAC_DEFERRAL_ERROR", feedback: "Incorrect. Indian IRDAI regulations prohibit deferral of acquisition expenses." }] },
            { stage: 3, scenario: "During statutory audit, Apex Shield presents financial statements omitting certain non-mandated secret reserves protected under Section 129(1) proviso of Companies Act 2013.", question: "Does this omission prevent financial statements from showing a True and Fair view under insurance rules?", options: [{ id: "A", text: "No, statements are treated as true and fair even if they omit matters exempt under Insurance Act / IRDA Act provisos", isCorrect: true, financialImpact: {}, feedback: "Correct. Section 129(1) third proviso protects insurance enterprises from being labeled misleading for omitting non-mandated items." }, { id: "B", text: "Yes, any omission of internal reserves renders financial statements false and misleading", isCorrect: false, misc: "MIS_TRUE_FAIR_INSURANCE_PROVISO_ERROR", feedback: "Incorrect. The law provides specific safe-harbor provisos for insurance form accounts." }] }
        ]
    },
    exam: [
        { id: "u11_q1", question: "1. The preparation and presentation of financial statements of General Insurance companies in India are governed by:", options: [{ id: "A", text: "Schedule III to the Companies Act 2013 only", isCorrect: false, misc: "MIS_SCH3_ONLY" }, { id: "B", text: "IRDAI Regulations 2000 & 2002 (Schedule B)", isCorrect: true }], explanation: "IRDAI Regulations 2000 & 2002 Schedule B prescribe mandatory Form Accounts for non-life insurers." },
        { id: "u11_q2", question: "2. Form A-RA represents which statutory financial statement?", options: [{ id: "A", text: "Revenue Account for Fire, Marine, and Miscellaneous segments", isCorrect: true }, { id: "B", text: "Profit & Loss Appropriation Account", isCorrect: false, misc: "MIS_RA_PL" }], explanation: "Form A-RA is the departmental Revenue Account." },
        { id: "u11_q3", question: "3. How many primary financial schedules are mandated under Schedule B for non-life insurers?", options: [{ id: "A", text: "15 Statutory Schedules", isCorrect: true }, { id: "B", text: "5 Schedules", isCorrect: false, misc: "MIS_SCH_5" }], explanation: "Schedules 1 through 15 cover premiums, claims, reserves, and assets." },
        { id: "u11_q4", question: "4. Under IRDAI Accounting Principle 3, acquisition costs are:", options: [{ id: "A", text: "Expensed in the period in which they are incurred", isCorrect: true }, { id: "B", text: "Capitalized as intangible assets", isCorrect: false, misc: "MIS_ACQ_CAP" }], explanation: "Deferral of acquisition costs is prohibited." },
        { id: "v11_q5", question: "5. The statutory Auditor's Report must certify:", options: [{ id: "A", text: "True and fair view and compliance with IRDAI regulations", isCorrect: true }, { id: "B", text: "Only income tax filing status", isCorrect: false, misc: "MIS_AUD_TAX" }], explanation: "Auditors verify compliance with regulatory norms." },
        { id: "u11_q6", question: "6. Separate Revenue Accounts must be maintained for:", options: [{ id: "A", text: "Fire, Marine, and Miscellaneous business lines", isCorrect: true }, { id: "B", text: "Head office salaries only", isCorrect: false, misc: "MIS_REV_HEAD" }], explanation: "Departmental segregation is mandatory." },
        { id: "u11_q7", question: "7. Cash Flow Statements under IRDAI regulations must use:", options: [{ id: "A", text: "Direct Method exclusively", isCorrect: true }, { id: "B", text: "Indirect Method exclusively", isCorrect: false, misc: "MIS_CF_IND" }], explanation: "Indirect method is carved out and prohibited." },
        { id: "u11_q8", question: "8. Management Report requirements include confirmation of:", options: [{ id: "A", text: "Solvency margin adequacy and registration validity", isCorrect: true }, { id: "B", text: "Employee personal investment portfolios", isCorrect: false, misc: "MIS_MR_EMP" }], explanation: "Management must confirm solvency adequacy." },
        { id: "u11_q9", question: "9. Premium Deficiency Reserve (PDR) is triggered when:", options: [{ id: "A", text: "Expected claims and expenses exceed URR reserves", isCorrect: true }, { id: "B", text: "Bank balances exceed share capital", isCorrect: false, misc: "MIS_PDR_CASH" }], explanation: "Prudence mandates provisioning underwriting deficits." },
        { id: "u11_q10", question: "10. Which act empowers IRDAI to frame financial reporting regulations?", options: [{ id: "A", text: "Insurance Act 1938 and IRDA Act 1999", isCorrect: true }, { id: "B", text: "Banking Regulation Act 1949", isCorrect: false, misc: "MIS_ACT_BANK" }], explanation: "Section 11(1) of Insurance Act and Section 26 of IRDA Act provide authority." }
    ]
};